### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by sherinsunny007** [therealbill/redskull#38] opened 2016-01-04 19:23 UTC
Hi,
I am getting the below error while doing go build to install redskul.

 redskull]# go build
can't load package: package src/github.com/therealbill/redskull: code in directory /usr/local/go/src/src/github.com/therealbill/redskull expects import "github.com/therealbill/redskull"

Please let me know the solution.

Thanks
Sunny

**Comment by therealbill** [comment] 2016-01-04 19:25
Hmm it looks like you have an extra "src" directory in your Go path. Did you clone the repo or use `go get`? I'd check to ensure you have it in `/usr/local/go/src/github.com/...` instead of `/usr/local/go/src/src/github.com`.

**Comment by sherinsunny007** [comment] 2016-01-04 19:31
I used go get

On Mon, Jan 4, 2016 at 11:26 AM, Bill Anderson <notifications@github.com>
wrote:

> Hmm it looks like you have an extra "src" directory in your Go path. Did
> you clone the repo or use go get? I'd check to ensure you have it in
> /usr/local/go/src/github.com/... instead of /usr/local/go/src/src/
> github.com/....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/therealbill/redskull/issues/38#issuecomment-168777278>
> .
>



-- 
Regards
Sherin Sunny
Devops

**Comment by sherinsunny007** [comment] 2016-01-04 19:36
I dont know from where it is taking the gopath value:


redis1 redskull]# cat /etc/profile.d/go.sh
export GOROOT=/usr/local/go
export GOPATH=$GOROOT/src
export PATH=$GOROOT/bin:$PATH
Above is my path in go.sh but when I do a build it is taking everything from src/src

redskull]# go build
../libredis/client/redis.go:84:2: cannot find package "bufio" in any of:
        /usr/local/go/src/bufio (from $GOROOT)
        /usr/local/go/src/src/bufio (from $GOPATH)

**Comment by therealbill** [comment] 2016-01-04 20:07
`export GOPATH=$GOROOT/src` <-- there is the problem. You're adding a src directory to the GOPATH. Personally I use `export GOPATH=$HOME/.go` so I can keep my user-level stuff local. But ultimately the problem is having /src in the path as a proper GOPATH has src *under* it instead.  As such it is treating 'src' as a repo location where normally it would be, for example,  'github.com'. 

You can also see it in the output where it is showing the difference between GOROOT and GOPATH. That said that it can't find buffo is a bit disconcerting for your Go installation, but maybe the multiple src directory is confusing it.

See https://golang.org/pkg/go/build/ for details on GOPATH. Mainly, don't add /src and I *highly* recommend not using GOROOT.

**Comment by sherinsunny007** [comment] 2016-01-04 20:26
Is the below settings fine?

edis1 vagrant]# cat /etc/profile.d/go.sh
export GOROOT=/usr/local/go
export GOPATH=/home/vagrant/
export PATH=$GOROOT/bin:$PATH

I am getting the below errors while running "go build" command:

edis1 redskull]# /usr/local/go/bin/go build
rpcserver.go:4:2: cannot find package "encoding/gob" in any of:
        /usr/local/go/src/encoding/gob (from $GOROOT)
        /home/vagrant/src/encoding/gob (from $GOPATH)
main.go:4:2: cannot find package "encoding/json" in any of:
        /usr/local/go/src/encoding/json (from $GOROOT)
        /home/vagrant/src/encoding/json (from $GOPATH)
rpcserver.go:5:2: cannot find package "errors" in any of:
        /usr/local/go/src/errors (from $GOROOT)


I am running the build frm the below path now:

/home/vagrant/redskull/


But there is no github.com folder in any of my path.


On Mon, Jan 4, 2016 at 12:12 PM, Bill Anderson <notifications@github.com>
wrote:

> export GOPATH=$GOROOT/src <-- there is the problem. You're adding a src
> directory to the GOPATH. Personally I use export GOPATH=$HOME/.go so I
> can keep my user-level stuff local. But ultimately the problem is having
> /src in the path as a proper GOPATH has src *under* it instead. As such
> it is treating 'src' as a repo location where normally it would be, for
> example, 'github.com'.
>
> You can also see it in the output where it is showing the difference
> between GOROOT and GOPATH. That said that it can't find buffo is a bit
> disconcerting for your Go installation, but maybe the multiple src
> directory is confusing it.
>
> See https://golang.org/pkg/go/build/ for details on GOPATH. Mainly, don't
> add /src and I *highly* recommend not using GOROOT.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/therealbill/redskull/issues/38#issuecomment-168790721>
> .
>



-- 
Regards
Sherin Sunny
Devops

**Comment by therealbill** [comment] 2016-01-04 20:33
I would use `/home/vagrant/go` as the GOPATH. Then when you `go get github.com/therealbill/redskull` it should create the tree structure in there as follows:

```bash
/home/vagrant/go/
      src/
          github.com/
               therealbill/
                    redskull/
      bin/
      pkg/
```

I'd also change the PATH statement to add `$GOPATH/bin` BTW. The fact that it isn't finding standard library packages makes me question if Go is properly installed to /usr/local/go.  What does `ls $GOROOT/` show? It should show the README.md, some other markdown files, bin, doc, src, and several other directories. 

If you `ls $GOROOT/src` you should see several directories including `buffo` and `errors` as well as `encoding`. If not your Go installation is not correct/complete.

**Comment by sherinsunny007** [comment] 2016-01-04 20:45
Thanks. I corrected it but my redis-sentinel conf file path is different. it is /etc/redis-sentinel.conf instead of /etc/redis/sentinel.conf. So I get the below error while starting redis skul. Where can I correct the path ?

@ redskull]# ./redskull
2016/01/04 20:42:38.465728 Launch Config: {Name: Port:0 IP: SentinelConfigFile: GroupName: BindAddress: SentinelHostAddress: TemplateDirectory: NodeRefreshInterval:60 RPCPort:0}
2016/01/04 20:42:38.465762 ENV contained no port, using default
2016/01/04 20:42:38.465768 binding to ':8000'
2016/01/04 20:42:38.465779 ENV contained no SentinelConfigFile, using default
2016/01/04 20:42:38.465784 ENV contained no GroupName, using default:redskull:1
2016/01/04 20:42:38.465863 Config: {"Name":"","Port":8000,"IP":"","SentinelConfigFile":"/etc/redis/sentinel.conf","GroupName":"redskull:1","BindAddress":"","SentinelHostAddress":"","TemplateDirectory":"","NodeRefreshInterval":60,"RPCPort":8001}
2016/01/04 20:42:38.466752 open /etc/redis/sentinel.conf: no such file or directory
2016/01/04 20:42:38.466762 Initializing LOCAL sentinel
2016/01/04 20:42:38.466766 No Hostname, determining local hostname
2016/01/04 20:42:38.466966 [127.0.0.1 ]
2016/01/04 20:42:38.466973 Determined LOCAL address is: 127.0.0.1:0
2016/01/04 20:42:38.466977 Determined LOCAL name is: 127.0.0.1:0
2016/01/04 20:42:38.468263 LOCAL Sentinel '127.0.0.1:0' failed connection attempt

**Comment by sherinsunny007** [comment] 2016-01-04 20:47
I created a soft link to the actual sentinel conf. Also please let me know how can I see the web interface ?

**Comment by therealbill** [comment] 2016-01-04 20:49
See the Getting Started guide at http://redskull.io/guide/gettingstarted-part1/ it will walk you through it. By default RS runs on port 8000 of the host it is running on.

**Comment by sherinsunny007** [comment] 2016-01-04 20:51
Thanks.

Iam planning to have 2 redis servers in one data center and other 2 in other datacenter. One shuld be master. How many sentinels do u suggest for this structure ? Also is it gud to have one master and one slave in one datacenter and remaining 2 slaves in other datacenter or do we need to have seperate masters in 2 datacenters ? I need the master from one Datacenter to replicate to the slaves in other datacenter

**Comment by therealbill** [comment] 2016-01-04 20:52
You're most welcome.

As to your Sentinel layout questions, I'd direct you to the Redis mailing list as it is too involved and detailed for Github issues. ;)

**Comment by sherinsunny007** [comment] 2016-01-04 20:54
pls let me know how can I access the redis mailing list ?

On Mon, Jan 4, 2016 at 12:53 PM, Bill Anderson <notifications@github.com>
wrote:

> You're most welcome.
>
> As to your Sentinel layout questions, I'd direct you to the Redis mailing
> list as it is too involved and detailed for Github issues. ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/therealbill/redskull/issues/38#issuecomment-168805420>
> .
>



-- 
Regards
Sherin Sunny
Devops

**Comment by sherinsunny007** [comment] 2016-01-04 20:55
Also does this redis skull makes any changes in my current redis-sentinel configuration ?

**Comment by therealbill** [comment] 2016-01-04 20:58
ML: https://groups.google.com/forum/#!forum/redis-db

Redskull will not make changes to Sentinel directly. If you alter your pod's configuration via Redskull such as by adding a slave to an existing pair *Sentinel* will modify the file for you a part of it's normal behavior.

Closing this as the original question around building has been addressed.

**Closed by therealbill** 2016-01-04 20:58 UTC
Labels: question

**Comment by sherinsunny007** [comment] 2016-01-04 21:01
Pod means just a master?

On Mon, Jan 4, 2016 at 12:58 PM, Bill Anderson <notifications@github.com>
wrote:

> ML: https://groups.google.com/forum/#!forum/redis-db
>
> Redskull will not make changes to Sentinel directly. If you alter your
> pod's configuration via Redskull such as by adding a slave to an existing
> pair *Sentinel* will modify the file for you a part of it's normal
> behavior.
>
> Closing this as the original question around building has been addressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/therealbill/redskull/issues/38#issuecomment-168806838>
> .
>



-- 
Regards
Sherin Sunny
Devops

**Comment by therealbill** [comment] 2016-01-04 21:02
http://redskull.io/guide/terminology/

**Comment by sherinsunny007** [comment] 2016-01-04 21:13
Thank You !

On Mon, Jan 4, 2016 at 1:02 PM, Bill Anderson <notifications@github.com>
wrote:

> http://redskull.io/guide/terminology/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/therealbill/redskull/issues/38#issuecomment-168807733>
> .
>



-- 
Regards
Sherin Sunny
Devops

**Comment by sherinsunny007** [comment] 2016-01-04 21:18
I have 3 slaves connected to redis master. I installed redis skull only in
master. But it is showing that no slaves are connected to it. cant I
monitor everything from one redis skull or do I need to install redis skull
in all slaves too ?

[image: Inline image 1]

On Mon, Jan 4, 2016 at 1:13 PM, Sherin Sunny <sherin.sunny@shipwire.com>
wrote:

> Thank You !
>
> On Mon, Jan 4, 2016 at 1:02 PM, Bill Anderson <notifications@github.com>
> wrote:
>
>> http://redskull.io/guide/terminology/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/therealbill/redskull/issues/38#issuecomment-168807733>
>> .
>>
>
>
>
> --
> Regards
> Sherin Sunny
> Devops
>



-- 
Regards
Sherin Sunny
Devops

**Comment by therealbill** [comment] 2016-01-04 21:19
Sherin, Please open a new GH issue for new questions. Or if you use Slack send me your email address and I can send you an invite to the Redskull Slack server.

**Comment by sherinsunny007** [comment] 2016-01-04 22:29
I would like you to please help me with your vast experience in redis regarding the layout.

So could you please tell me the 
1.) Number of sentinels needed for monitoring one master and 3 slaves in 2 datacenters
2.) Do I need to install redskul in all slaves to get the correct information or one red skull in one master can give the entire information ?
